# rfsimulator chanmod: flat Rayleigh (1 tap) DL+UL
# DL @ UE RX: rfsimu_channel_enB0 | UL @ gNB RX: rfsimu_channel_ue0
channelmod = {
  max_chan = 10;
  modellist = "modellist_rfsimu_rayleigh1";
  modellist_rfsimu_rayleigh1 = (
    {
      model_name       = "rfsimu_channel_enB0"
      type             = "Rayleigh1";
      ploss_dB         = 0;
      noise_power_dB   = -35;
      forgetfact       = 0.3;
      offset           = 0;
      ds_tdl           = 0;
    },
    {
      model_name       = "rfsimu_channel_ue0"
      type             = "Rayleigh1";
      ploss_dB         = 0;
      noise_power_dB   = -35;
      forgetfact       = 0.3;
      offset           = 0;
      ds_tdl           = 0;
    }
  );
};
