# TDL-A는 DL(UE RX, rfsimu_channel_enB0)만. UL(gNB RX, rfsimu_channel_ue0)은 페이딩 없이 이상에 가깝게(AWGN 단위 + 극소 잡음).
channelmod = {
  max_chan = 10;
  modellist = "modellist_rfsimu_tdl_a_dl_ul_ideal";
  modellist_rfsimu_tdl_a_dl_ul_ideal = (
    {
      model_name       = "rfsimu_channel_enB0"
      type             = "TDL_A";
      ploss_dB         = 0;
      noise_power_dB   = -35;
      forgetfact       = 0.3;
      offset           = 0;
      ds_tdl           = 100e-9;
    },
    {
      model_name      = "rfsimu_channel_ue0"
      type            = "AWGN";
      ploss_dB        = 0;
      noise_power_dB  = -120;
      forgetfact      = 0.0;
      offset          = 0;
    }
  );
};
