# TDL-A for rfsimulator (--rfsimulator.options chanmod)
# DL: UE가 적용하는 모델 이름 rfsimu_channel_enB0
# UL: gNB가 적용하는 모델 이름 rfsimu_channel_ue0
channelmod = {
  max_chan = 10;
  modellist = "modellist_rfsimu_tdl_a";
  modellist_rfsimu_tdl_a = (
    {
      model_name       = "rfsimu_channel_enB0"
      type             = "TDL_A";
      ploss_dB         = 0;
      noise_power_dB   = -35;
      forgetfact       = 0.3;
      offset           = 0;
      ds_tdl           = 100e-9;
    },
    {
      model_name       = "rfsimu_channel_ue0"
      type             = "TDL_A";
      ploss_dB         = 0;
      noise_power_dB   = -35;
      forgetfact       = 0.3;
      offset           = 0;
      ds_tdl           = 100e-9;
    }
  );
};

