# TDL-A dynamic profile for rfsimulator chanmod
channelmod = {
  max_chan = 10;
  modellist = "modellist_rfsimu_tdl_a_dyn";
  modellist_rfsimu_tdl_a_dyn = (
    {
      model_name       = "rfsimu_channel_enB0"
      type             = "TDL_A";
      ploss_dB         = 0;
      noise_power_dB   = -70;
      forgetfact       = 0.2;
      offset           = 0;
      ds_tdl           = 300e-9;
    },
    {
      model_name       = "rfsimu_channel_ue0"
      type             = "TDL_A";
      ploss_dB         = 0;
      noise_power_dB   = -70;
      forgetfact       = 0.2;
      offset           = 0;
      ds_tdl           = 300e-9;
    }
  );
};
